media_folder: 'static/images'
public_folder: '/images'

# publish_mode: editorial_workflow

backend:
  name: github
  repo: bdadam/nezdmeg.com

collections:
  - name: article
    label: Article
    folder: articles
    create: true
    delete: false
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Date', name: 'datetime', widget: 'date', format: 'YYYY-MM-DD HH:mm' }
      - { label: 'Teaser', name: 'teaser', widget: 'markdown' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
